#ifndef RFLOW_HW_ROCKCHIP_MPP_VIDEO_DECODER_FACTORY_H_
#define RFLOW_HW_ROCKCHIP_MPP_VIDEO_DECODER_FACTORY_H_

#include "platform/rockchip/video_codec_factory.h"

#endif  // RFLOW_HW_ROCKCHIP_MPP_VIDEO_DECODER_FACTORY_H_
